/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ABTestVariants {
  'variantA' : bigint,
  'variantB' : bigint,
  'variantC' : bigint,
}
export type CallStatus = { 'closed' : null } |
  { 'pending' : null } |
  { 'contacted' : null } |
  { 'converted' : null };
export interface Lead {
  'id' : bigint,
  'age' : bigint,
  'pan' : string,
  'salary' : string,
  'loanAmount' : bigint,
  'callStatus' : CallStatus,
  'cibil' : bigint,
  'name' : string,
  'email' : string,
  'abVariant' : string,
  'timestamp' : bigint,
  'phone' : string,
  'selectedLenders' : Array<string>,
}
export interface LeadsStats {
  'convertedCount' : bigint,
  'totalLeads' : bigint,
  'totalRevenueEstimate' : bigint,
}
export interface Lender {
  'id' : bigint,
  'maxAmount' : bigint,
  'processingFee' : string,
  'minCibil' : bigint,
  'name' : string,
  'badges' : Array<string>,
  'interestRate' : string,
  'category' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getLeadsStats' : ActorMethod<[], LeadsStats>,
  'getLenders' : ActorMethod<[], Array<Lender>>,
  'getLendersByCibil' : ActorMethod<[bigint], Array<Lender>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVariantStats' : ActorMethod<[], ABTestVariants>,
  'initLenders' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordVariant' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLead' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      bigint,
      Array<string>,
      string,
    ],
    bigint
  >,
  'updateLeadStatus' : ActorMethod<[bigint, CallStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];