/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CallStatus = IDL.Variant({
  'closed' : IDL.Null,
  'pending' : IDL.Null,
  'contacted' : IDL.Null,
  'converted' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'pan' : IDL.Text,
  'salary' : IDL.Text,
  'loanAmount' : IDL.Nat,
  'callStatus' : CallStatus,
  'cibil' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'abVariant' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'selectedLenders' : IDL.Vec(IDL.Text),
});
export const LeadsStats = IDL.Record({
  'convertedCount' : IDL.Nat,
  'totalLeads' : IDL.Nat,
  'totalRevenueEstimate' : IDL.Nat,
});
export const Lender = IDL.Record({
  'id' : IDL.Nat,
  'maxAmount' : IDL.Nat,
  'processingFee' : IDL.Text,
  'minCibil' : IDL.Nat,
  'name' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'interestRate' : IDL.Text,
  'category' : IDL.Text,
});
export const ABTestVariants = IDL.Record({
  'variantA' : IDL.Nat,
  'variantB' : IDL.Nat,
  'variantC' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLeadsStats' : IDL.Func([], [LeadsStats], ['query']),
  'getLenders' : IDL.Func([], [IDL.Vec(Lender)], ['query']),
  'getLendersByCibil' : IDL.Func([IDL.Nat], [IDL.Vec(Lender)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVariantStats' : IDL.Func([], [ABTestVariants], ['query']),
  'initLenders' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordVariant' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'updateLeadStatus' : IDL.Func([IDL.Nat, CallStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CallStatus = IDL.Variant({
    'closed' : IDL.Null,
    'pending' : IDL.Null,
    'contacted' : IDL.Null,
    'converted' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'pan' : IDL.Text,
    'salary' : IDL.Text,
    'loanAmount' : IDL.Nat,
    'callStatus' : CallStatus,
    'cibil' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'abVariant' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'selectedLenders' : IDL.Vec(IDL.Text),
  });
  const LeadsStats = IDL.Record({
    'convertedCount' : IDL.Nat,
    'totalLeads' : IDL.Nat,
    'totalRevenueEstimate' : IDL.Nat,
  });
  const Lender = IDL.Record({
    'id' : IDL.Nat,
    'maxAmount' : IDL.Nat,
    'processingFee' : IDL.Text,
    'minCibil' : IDL.Nat,
    'name' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'interestRate' : IDL.Text,
    'category' : IDL.Text,
  });
  const ABTestVariants = IDL.Record({
    'variantA' : IDL.Nat,
    'variantB' : IDL.Nat,
    'variantC' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLeadsStats' : IDL.Func([], [LeadsStats], ['query']),
    'getLenders' : IDL.Func([], [IDL.Vec(Lender)], ['query']),
    'getLendersByCibil' : IDL.Func([IDL.Nat], [IDL.Vec(Lender)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVariantStats' : IDL.Func([], [ABTestVariants], ['query']),
    'initLenders' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordVariant' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'updateLeadStatus' : IDL.Func([IDL.Nat, CallStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };